name: "Case 2: L2 only"

permissions:
  contents: read
  packages: write

on:
  workflow_dispatch:
  push:

jobs:
  detect_changes:

    runs-on: ubuntu-latest
    outputs:
      l1: ${{ steps.changes.outputs.l1 }}
      l2: ${{ steps.changes.outputs.l2 }}
      workflow: ${{ steps.changes.outputs.workflow }}
    steps:
      - id: changes
        run: |
          # set-output here, e.g. via $GITHUB_OUTPUT
          echo "l1=false"  >> "$GITHUB_OUTPUT"
          echo "l2=true"  >> "$GITHUB_OUTPUT"
  
  l1:
    needs:
      - detect_changes
    if: ${{ needs.detect_changes.outputs.l1 == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "l1"

  test_l1:
    needs:
      - l1
    runs-on: ubuntu-latest
    steps:
      - run: echo "test l1"

  l2:
    needs: [detect_changes, test_l1]
    # run only if needed; after job2 if it ran, otherwise right after job1
    if: ${{ always()
           && needs.detect_changes.outputs.l2 == 'true'
           && (needs.test_l1.result == 'success' || needs.test_l1.result == 'skipped') }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "l2"

  test_l2:
    needs:
      - l2
    if: ${{ always()
           && (needs.l2.result == 'success' || needs.l2.result == 'skipped') }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "test l2"