---
name: Test 2 in feature 1
on:
  pull_request:
  workflow_dispatch:

concurrency:
  group: foo
  cancel-in-progress: false

jobs:
  deploy:
    name: Deploy feature 1
    concurrency:
      group: ${{ github.workflow }}-deploy-pr-${{ github.event.pull_request.number || github.run_id }}
      cancel-in-progress: true
    runs-on: ubuntu-latest
    steps:
      - run: sleep 180

  test:
    name: Test feature 1
    needs:
      - deploy
    concurrency:
      group: ${{ github.workflow }}-test-pr-${{ github.event.pull_request.number || github.run_id }}
      cancel-in-progress: true
    runs-on: ubuntu-latest
    steps:
      - run: sleep 180

  cleanup:
    needs:
      - test
    if: ${{ always() }}
    runs-on: ubuntu-latest
    steps:
      - run: cleanup
