name: CI image

permissions:
  contents: read
  packages: write

on:
  workflow_dispatch:
  push:

jobs:

  pre:

    runs-on: ubuntu-24.04
    steps:
    - name: delay
      if: always()
      run: sleep 120s

    - name: Debug
      run: echo ok
    
    - name: after
      if: always()
      run: sleep 120s
