
on:
  pull_request:
  workflow_dispatch:

jobs:
  deploy:
    concurrency:
      group: ${{ github.workflow }}-${{ github.job }}-pr-${{ github.event.pull_request.number || github.run_id }}
      cancel-in-progress: true
    runs-on: ubuntu-latest
    steps:
      - run: sleep 180

  test:
    needs:
      - deploy
    concurrency:
      group: ${{ github.workflow }}-${{ github.job }}-pr-${{ github.event.pull_request.number || github.run_id }}
      cancel-in-progress: true
    runs-on: ubuntu-latest
    steps:
      - run: sleep 180

  cleanup:
    needs:
      - test
    if: ${{ always() }}
    runs-on: ubuntu-latest
    steps:
      - run: cleanup
