name: CI image

permissions:
  contents: read
  packages: write

on:
  workflow_dispatch:
  push:

jobs:
  pre:

    if: always()
    runs-on: ubuntu-24.04
    timeout-minutes: 1
    steps:
    - name: create
      run: sleep 2

  main:
    needs:
      - pre
    runs-on: ubuntu-24.04
    steps:
    - name: main
      run: sleep 120
    - name: finale
      if: always()
      run: echo finale
  post:
    if: always()
    needs:
      - main
    runs-on: ubuntu-24.04
    steps:
    - name: destroy
      run: sleep 2
